version: "3.8"

services:
  client:
    build:
      context: ./client-side
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./client-side:/client
    command: npm run start
